source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/SilenceWater/Specs.git'

platform :ios, '8.0'
target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

    pod 'DYNetwork'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
